// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkDataLayer.Mappers;

namespace ParkDataLayer.Migrations
{
    [DbContext(typeof(ParkbeheerContext))]
    [Migration("20220109185751_relatieTussenAlles")]
    partial class relatieTussenAlles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkDataLayer.Model.Huis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<int>("Nummer")
                        .HasColumnType("int");

                    b.Property<string>("ParkId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Straat")
                        .HasColumnType("Varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ParkId");

                    b.ToTable("Huizen");
                });

            modelBuilder.Entity("ParkDataLayer.Model.Huurcontract", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("Varchar(25)");

                    b.Property<int>("AantalDagen")
                        .HasColumnType("int");

                    b.Property<DateTime>("EindDatum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HuisId")
                        .HasColumnType("int");

                    b.Property<int?>("HuurderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HuisId");

                    b.HasIndex("HuurderId");

                    b.ToTable("Huurcontracten");
                });

            modelBuilder.Entity("ParkDataLayer.Model.Huurder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Telefoon")
                        .HasColumnType("Varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Huurders");
                });

            modelBuilder.Entity("ParkDataLayer.Model.Park", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Locatie")
                        .HasColumnType("Varchar(500)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Parken");
                });

            modelBuilder.Entity("ParkDataLayer.Model.Huis", b =>
                {
                    b.HasOne("ParkDataLayer.Model.Park", "Park")
                        .WithMany("Huizen")
                        .HasForeignKey("ParkId");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("ParkDataLayer.Model.Huurcontract", b =>
                {
                    b.HasOne("ParkDataLayer.Model.Huis", "Huis")
                        .WithMany("Huurcontracts")
                        .HasForeignKey("HuisId");

                    b.HasOne("ParkDataLayer.Model.Huurder", "Huurder")
                        .WithMany()
                        .HasForeignKey("HuurderId");

                    b.Navigation("Huis");

                    b.Navigation("Huurder");
                });

            modelBuilder.Entity("ParkDataLayer.Model.Huis", b =>
                {
                    b.Navigation("Huurcontracts");
                });

            modelBuilder.Entity("ParkDataLayer.Model.Park", b =>
                {
                    b.Navigation("Huizen");
                });
#pragma warning restore 612, 618
        }
    }
}
